application: polybeegae
version: 1
runtime: go
api_version: go1

handlers:


- url: /bower_components/
  static_dir: bower_components

- url: /scripts/
  static_dir: scripts

- url: /styles/
  static_dir: styles

- url: /images/
  static_dir: images

- url: /json/
  static_dir: json
 
- url: /elements.html
  static_files: dist/elements/elements.vulcanized.html
  upload: dist/elements/elements.vulcanized.html
  
- url: /static/
  static_dir: static

- url: /polymerapp/
  static_dir: dist

- url: /.*
  script: _go_app
  
